# Generated by Django 2.1.2 on 2019-03-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.SmallIntegerField(choices=[(1, 'Kingdom'), (2, 'Group'), (3, 'Subgroup')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psmd.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.CharField(max_length=20)),
                ('species_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('biosample', models.CharField(max_length=15)),
                ('bioproject', models.CharField(max_length=15)),
                ('assembly_level', models.CharField(max_length=15)),
                ('assembly_accession', models.CharField(help_text='assembly accession in genbank', max_length=20)),
                ('download_accession', models.CharField(help_text='accession of used sequence file', max_length=20)),
                ('gene_count', models.IntegerField()),
                ('size', models.BigIntegerField()),
                ('gc_content', models.FloatField()),
                ('ssr_count', models.IntegerField()),
                ('ssr_frequency', models.FloatField()),
                ('ssr_density', models.FloatField()),
                ('cover', models.FloatField()),
                ('cm_count', models.IntegerField()),
                ('cm_frequency', models.FloatField()),
                ('cm_density', models.FloatField()),
                ('cssr_percent', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psmd.Category')),
            ],
            options={
                'db_table': 'genome',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10)),
                ('fasta', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=5)),
                ('parameter', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Success'), (3, 'Failure')], default=0)),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
