# Generated by Django 2.1.2 on 2019-03-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panmicrosatdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cssr',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='cssrannot',
            name='cssr',
        ),
        migrations.RemoveField(
            model_name='cssrannot',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='cssrmeta',
            name='cssr',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='sequence',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.RemoveField(
            model_name='ssr',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='ssrannot',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='ssrannot',
            name='ssr',
        ),
        migrations.RemoveField(
            model_name='ssrmeta',
            name='ssr',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='CSSR',
        ),
        migrations.DeleteModel(
            name='CSSRAnnot',
        ),
        migrations.DeleteModel(
            name='CSSRMeta',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='SSR',
        ),
        migrations.DeleteModel(
            name='SSRAnnot',
        ),
        migrations.DeleteModel(
            name='SSRMeta',
        ),
    ]
