# Generated by Django 2.1.7 on 2019-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0002_auto_20190321_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='parameter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ssrannot',
            name='location',
            field=models.SmallIntegerField(choices=[(1, 'CDS'), (2, 'exon'), (3, '3UTR'), (4, 'intron'), (5, '5UTR')]),
        ),
    ]
