# Generated by Django 2.1.2 on 2019-03-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0002_auto_20190314_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Success'), (3, 'Failure')], default=0)),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
