# Generated by Django 2.0 on 2019-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0002_auto_20190324_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='issrmeta',
            name='self_seq',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
