# Generated by Django 2.1.7 on 2019-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0003_issrmeta_self_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.SmallIntegerField(choices=[(1, 'version'), (2, 'news')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
