# Generated by Django 2.1.7 on 2019-03-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0003_auto_20190322_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cssrannot',
            old_name='gene_id',
            new_name='gene',
        ),
    ]
