# Generated by Django 2.1.7 on 2019-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmd', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='abstract',
            field=models.TextField(),
        ),
    ]
